functionality:
  name: samtools
  namespace: gene_demulti
  description: Filter the BAM according to the instruction of scSplit via Samtools
  authors:
    - name: Xichen Wu
  arguments:
    - name: "--bam"
      type: file
      required: true
      description: "Input bam file for filtering."
    - name: "--id"
      type: string
      default: "samtools"
    - name: "--output"
      type: file
      direction: output
      description: "Samtools output directory."
      example: "samtools_out/"
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: wxicu/demultiplex_samtools:latest
  - type: nextflow
    variant: vdsl3
    directives:
       container: wxicu/demultiplex_samtools:latest
