functionality:
  name: "bbknn_leiden"
  namespace: "integration/common"
  description: "Run bbknn followed by leiden clustering and run umap on the result."
  authors:
    - __merge__: ../../../../src/authors/mauro_saporita.yaml
      roles: [ author ]
    - __merge__: ../../../../src/authors/povilas_gibas.yaml
      roles: [ author ]
  argument_groups:
    - name: "Inputs"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          required: true
          type: file
          description: Path to the sample.
          example: dataset.h5mu
        - name: "--layer"
          default: "log_normalized"
          type: string
          description: use specified layer for expression values instead of the .X object from the modality.
          required: false
        - name: "--obsm_input"
          description: The dimensionality reduction in `.obsm` to use for neighbour detection. Defaults to X_pca.
          type: string
          default: "X_pca"
        - name: "--obs_batch"
          type: string
          description: .obs column name discriminating between your batches.
          default: "sample_id"
    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: Bbknn
      arguments:
        - name: "--n_neighbors_within_batch"
          type: integer
          description: How many top neighbours to report for each batch; total number of neighbours in the initial k-nearest-neighbours computation will be this number times the number of batches.
          default: 3
        - name: "--n_pcs"
          type: integer
          description: How many dimensions (in case of PCA, principal components) to use in the analysis.
          default: 50
        - name: "--n_trim"
          type: integer
          description: Trim the neighbours of each cell to these many top connectivities. May help with population independence and improve the tidiness of clustering. The lower the value the more independent the individual populations, at the cost of more conserved batch effect. If `None` (default), sets the parameter value automatically to 10 times `neighbors_within_batch` times the number of batches. Set to 0 to skip.
    - name: Clustering options
      arguments:
        - name: "--obs_cluster"
          type: string
          description: |
            Prefix for the .obs keys under which to add the cluster labels. Newly created columns in .obs will 
            be created from the specified value for '--obs_cluster' suffixed with an underscore and one of the resolutions
            resolutions specified in '--leiden_resolution'.          
          default: "harmony_integration_leiden"
        - name: "--leiden_resolution"
          type: double
          description: Control the coarseness of the clustering. Higher values lead to more clusters.
          default: 1
    - name: Umap options
      arguments:
        - name: "--obsm_umap"
          type: string
          default: "X_leiden_harmony_umap"
          required: false
          description: "In which .obsm slot to store the resulting UMAP embedding."
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/pbmc_1k_protein_v3