functionality:
  name: freemuxlet
  namespace: gene_demulti
  description: |
    Run Freemuxlet |
    The same parameter with the same values as default between dsc-pileup and demuxlet are merged. |
    The same parameter with different default values between dsc-pileup and demuxlet are separated by the suffix.
  authors:
    - name: Xichen Wu
  argument_groups:
  - name: "Input"
    arguments:
    - name: "--id"
      type: string
      default: "freemuxlet"
    - name: "--sam"
      type: file
      description: "Input SAM/BAM/CRAM file. Must be sorted by coordinates and indexed."
    - name: "--tagGroup"
      type: string
      description: "ag representing readgroup or cell barcodes, in the case to partition the BAM file into multiple groups. For 10x genomics, use CB."
      default: 'CB'
    - name: "--tagUMI"
      type: string
      default: 'UB'
      description: "Tag representing UMIs. For 10x genomiucs, use UB."
    - name: "--excludeFlag"
      type: integer
      description: "SAM/BAM flag to exclude."
      default: 1796
    - name: "--vcf"
      type: file
      description: "Input VCF/BCF file, containing the AC and AN field."
    - name: "--sm"
      type: string
      description: "List of sample IDs to compare to (default: use all)."
    - name: "--smList"
      type: string
      description: "File containing the list of sample IDs to compare."
    - name: "--samVerbose"
      type: integer
      default: 1000000
      description: "Verbose message frequency for SAM/BAM/CRAM."
    - name: "--vcfVerbose"
      type: integer
      default: 1000
      description: "Verbose message frequency for VCF/BCF."
    - name: "--skipUmi"
      type: boolean_true
      description: "Do not generate [prefix].umi.gz file, which stores the regions covered by each barcode/UMI pair."
    - name: "--capBQDsc"
      type: integer
      default: 40
      description: "Maximum base quality (higher BQ will be capped) for dsc-pileup."
    - name: "--minBQ"
      type: integer
      default: 13
      description: "Minimum base quality to consider (lower BQ will be skipped)."
    - name: "--minMQ"
      type: integer
      default: 20
      description: "Minimum mapping quality to consider (lower MQ will be ignored)"
    - name: "--minTD"
      type: integer
      default: 0
      description: "Minimum distance to the tail (lower will be ignored)."
    - name: "--exclFlag"
      type: integer
      default: 3844
      description: "SAM/BAM FLAGs to be excluded."
    - name: "--groupList"
      type: string
      description: "List of tag readgroup/cell barcode to consider in this run. All other barcodes will be ignored. This is useful for parallelized run."
    - name: "--minTotal"
      type: integer
      default: 0
      description: "Minimum number of total reads for a droplet/cell to be considered."
    - name: "--minUniq"
      type: integer
      default: 0
      description: "Minimum number of unique reads (determined by UMI/SNP pair) for a droplet/cell to be considered."
    - name: "--minSnp"
      type: integer
      default: 0
      description: "Minimum number of SNPs with coverage for a droplet/cell to be considered."
    - name: "--plp"
      type: string
      description: "Prefix of input files generated by dsc-pileup"
    - name: "--initCluster"
      type: file
      description: "Input file containing the initial cluster information."
    - name: "--nsample"
      type: integer
      default: 2
      description: "Number of samples multiplexed together"
    - name: "--auxFiles"
      type: boolean_true
      description: "Turn on writing auxilary output files"
    - name: "--verbose"
      type: integer
      default: 100
      description: "Turn on verbose mode with specific verbosity threshold. 0: fully verbose, 100 : no verbose messages."
    - name: "--doubletPrior"
      type: double
      default: 0.5
      description: "Prior of doublet."
    - name: "--geneError"
      type: double
      default: 0.1
      description: "Genotype error parameter per cluster."
    - name: "--bfThres"
      type: double
      default: 5.41
      description: "Bayes Factor Threshold used in the initial clustering."
    - name: "--fracInitClust"
      type: double
      default: 1
      description: "Fraction of droplets to be clustered in the very first round of initial clustering procedure."
    - name: "--iterInit"
      type: integer
      default: 10
      description: "Iteration for initial cluster assignment (set to zero to skip the iterations)."
    - name: "--keepInitMissing"
      type: boolean_true
      description: "Keep missing cluster assignment as missing in the initial iteration."
    - name: "--randomizeSingletScore"
      type: boolean_true
      description: "Randomize the singlet scores to test its effect."
    - name: "--seed"
      type: integer
      default: 0
      description: "Seed for random number (use clocks if not set)."
    - name: "--capBQ"
      type: integer
      default: 20
      description: "Maximum base quality (higher BQ will be capped)."
    - name: "--minUmi"
      type: integer
      default: 0
      description: "Minimum number of UMIs for a droplet/cell to be considered."
  - name: "Output"
    arguments:
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      description: Output directory 
      example: "freemuxlet/"
    - name: "--outDsc"
      type: file
      direction: output
      description: dsc-pileup output file prefix
      example: "freemuxlet_dsc"
    - name: "--out"
      type: file
      direction: output
      description: freemuxlet Output file prefix
      example: "freemuxlet"

  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: wxicu/demultiplex_popscle
  - type: nextflow
    variant: vdsl3
    directives:
      label: [ midmem, midcpu ]
      container: wxicu/demultiplex_popscle
