functionality:
  name: bcftools
  namespace: gene_demulti
  description: Filter the variants called by freebayes or cellSNP
  authors:
    - name: Xichen Wu
  arguments:
    - name: "--vcf"
      type: file
      required: true
      multiple: true
      multiple_sep: ","
      description: VCF files, must have the same sample columns appearing in the same order.
    - name: "--id"
      type: string
      default: "bcftools"
    - name: "--concat"
      type: boolean_false
      description: Concatenate or combine VCFs and sort them.
    - name: "--filter"
      type: string
      default: "bcftools"
      description: "Filter VCFs with QUAL > 30."
    - name: "--output"
      type: file
      direction: output
      description: bcftools output directory
      example: "bcftools_out/"
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: biocontainers/bcftools:v1.9-1-deb_cv1
  - type: nextflow
    variant: vdsl3
    directives:
       container: biocontainers/bcftools:v1.9-1-deb_cv1
