functionality:
  name: summary
  namespace: gene_demulti
  description: |
    Analysis
  authors:
    - name: Xichen Wu
  argument_groups:
  - name: "Input"
    arguments:
    - name: --file
      type: string
      description: "Demultiplexing Output Files"
    - name: --barcode
      type: file
      description: Input Barcode File used for demultiplexing
  - name: "Output"
    arguments:
    - name: --output
      alternatives: [ "-o" ]
      type: file
      direction: output
      description: Output directory 
      example: "summary/"
  resources:
    - type: bash_script
      path: script.sh
    - type: r_script
      path: compareParam.R
platforms:
  - type: docker
    image: "wxicu/rpython:latest"
  - type: nextflow
    variant: vdsl3
    directives:
      label: [ lowmem, lowcpu ]
      container: wxicu/rpython:latest
setup:
  - type: r
    cran: [ argparse, R.utils, data.table, ggplot2, stringr, reshape2, dplyr, plyr, ggpubr ]