name: test ci

on:
  pull_request:
  push:

jobs:
  list_components:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.ns-list.outputs.components_json }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - uses: viash-io/viash-actions/setup@main
      id: install-viash
      with:
        version: 0.6.3
        registry: ghcr.io
        organization: openpipelines-bio
        target_image_source: https://github.com/openpipelines-bio/openpipeline

    - name: Check version of Viash
      run: |
        viash -h

    - uses: viash-io/viash-actions/ns-list@main
      id: ns-list

  # phase 2
  viash_test:
    needs: list_components
    if: ${{ needs.list_components.outputs.matrix != '[]' && needs.list_components.outputs.matrix != '' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list_components.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3

    - name: Fetch viash
      run: |
        bin/init -n
        bin/viash -h

    - name: Run test
      run: |
        bin/viash config view ${{ matrix.component.config.info }}