name: test ci

on:
  pull_request:
  push:

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - uses: viash-io/viash-actions/setup@main
    - name: Fetch viash
      run: |
        viash -h