name: test ci

on:
  pull_request:
  push:

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - uses: viash-io/viash-actions/setup@main
      with:
        version: develop
        registry: ghcr.io
        organization: openpipelines-bio
        target_image_source: https://github.com/openpipelines-bio/openpipeline

    - name: Check version of Viash
      run: |
        viash -h